#! /usr/bin/env bash
export BUNDLE_GEMFILE=$(pwd)/Gemfile

HAS_BUNDLER=`gem list --local | grep bundler`
if [ "$HAS_BUNDLER" = "" ]; then
  gem install bundler --no-rdoc --no-ri
fi

bundle check > /dev/null || bundle install
bundle exec rake -f Rakefile $@
